### ISSUE TITLE
SAMLRaider invalidating seemingly valid SAML responses

### ISSUE THREAD

**Issue by exploresecurity** [SAMLRaider/SAMLRaider#1]
Hi

I was really keen to explore SAMLRaider but I got a bit nervy about using it because it appeared to be making changes beyond what I would have expected. I would intercept the HTTP request carrying the SAML response, delete a character, replace it and then send it on its way – thus I've made no overall change - but it would be rejected. When looking at the edited response the plugin had:

-	stripped all the newlines out completely. As far as I understand it, canonicalization retains CRLFs (but ensures they are always 0x0a) so I assume therefore that any 0a byte is part of the input that’s digested.
-	taken out the attribute xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" from all elements that contained it (saml:Issuer, saml:Subject, saml:Condition, saml:AuthnStatement and saml:AttributeStatement). This presumably would change the digest of the assertion, assuming canonicalization retains the namespace attribute.

So in both cases the digest was being changed, thus invalidating the signature, hence the response . was rejected. Grateful for any comments.

Jerome

**Comment by RouLee** [comment]
Hi Jerome

Thank you for the bug report.
I tested what you wrote and could reproduce the removing of the namespaces and new lines with self made SAML messages. I will try to fix it in the next days.

My test IdP does not create SAML messages with new lines and also does not attach a namespace to the elements like Issuer or Subject. What product do you use for the IdP and the SP?
Perhaps I can integrate the same product into my test environment.

Cheers
Roland

**Comment by exploresecurity** [comment]
Hi Roland

Thanks for taking the time to investigate. The IDP was Salesforce but I don't know the details behind the SP because it was part of a blackbox penetration test and I don't know what they were using.

Cheers
Jerome

**Comment by RouLee** [comment]
Hi Jerome

Sorry for the big delay in fixing your issue. The namespaces are now no longer deleted and the line breaks are retained.
Unfortunately I do not have a Salesforce IdP for real life testing :)
I could only test it with an example assertion from the Salesforce website and validate it manually.
I would be glad if you could test the extension the next time you have to deal with such an IdP and send me your feedback.

Thanks again for the bug report.
Cheers
Roland

**Comment by exploresecurity** [comment]
Hi Roland

No worries. Maintaining an open source project is a thankless task - until now: thanks. When I next come across SAML I'll get the latest version of SAMLRaider and give it another go.

Jerome
