### ISSUE TITLE
Test all the attacks

### ISSUE THREAD

**Issue by dobin** [SAMLRaider/SAMLRaider#15]
I want to test all possible SAML attacks on a site. For this, i assumed the following workflow:

1) Send SAMLResponse login request to SAMLRaider
2) ???
3) Profit

Or, to be more exact:

1) Send SAMLResponse login request to SAMLRaider
2) Copy XML Signature
2.1) Send cert to saml raider certs
2.2) Clone cert / chain

3) Remove signatures
3.1) Check if login still works

4) Re-Sign assertion
4.1) Check if login still works

5) Re-sign message
5.1) Check if login still works

6) XSW[1-8] attack
6.0) Select XSW attack, click apply
6.1) Check if login still works
6.2) Reset message?

So my questions are:
- Does SAMLRaider work in Repeater, or do I have to intercept the SAMLResponse every time?
- Do i need to click "Reset message"? If yes, when? What does it do?
- Do the XSW attacks use the original SAML Assertion? If i have modified it (e.g. re-signed message, assertion etc.), do i have to reset the message? Is it taking the original message? The modified one? Which one makes more sense?
- Some XSW attacks are not working after I press "Apply XSW", e.g. "This XML Message is not suitable for this particular XSW attack". Is it possible to check the preconditions beforehand, and indicate in the XSW selection view which one's will work, and which one will not? (so i dont have to click through all of them)

**Comment by kingthorin** [comment]
@dobin this article might help you: http://research.aurainfosec.io/bypassing-saml20-SSO/

**Comment by mindfuckup** [comment]
Sorry, Dobin.

I guess this is too error prone to automate everything. Often it's even needed to perform the entire authentication over and over again. So I'll close the issue 😢

Best,
Mänu
