### ISSUE TITLE
Intercept: Request view selection Block

### ISSUE THREAD

**Issue by dobin** [SAMLRaider/SAMLRaider#16]
I cannot click on "Raw" anymore in intercept, when i selected SAMLRaider tab:
![image](https://cloud.githubusercontent.com/assets/3250886/19802632/ea720622-9d04-11e6-89c1-2b44e0bc865f.png)

**Comment by mindfuckup** [comment]
Hey Dobin

You can select the Raw tab again as soon as you receive a new message (either SAML or an arbitrary HTTP request):
![burpintercept2](https://user-images.githubusercontent.com/438188/86257936-7fc2b780-bbba-11ea-88f1-d87a35cadf44.gif)


So, this issue is closed then :)

Greetz!
Mänu
