### ISSUE TITLE
Not able to view the message editor part of SAML raider

### ISSUE THREAD

**Issue by boreddom** [SAMLRaider/SAMLRaider#24]
Installed the SAML raider  extension from BApp store, able to view only the SAML raider certificates tab...but unable to get a tab under proxy and repeater. Any specific configuration required?
SAML raider version 1.2.1
Burp suite version: 1.7.32

**Comment by mindfuckup** [comment]
Hi,

The tab only shows up if there is a SAML message. Do you have a SAML message in your request? They start with `SAMLResponse` or `SAMLRequest` and are in a HTTP GET parameter or as a parameter in the POST body.

Can you provide us an example SAML message where the extension does not work?

**Comment by boreddom** [comment]
Hi,
The saml message passes in a Soap service in an xml body with parameter
name samlObject.


Regards,
Vinod Kumar K

**Comment by mindfuckup** [comment]
The SOAP binding should be supported. Is it possible to have an example SAML message for testing?

**Comment by boreddom** [comment]
Sorry, the endpoint cannot be reached from outside..it is an internal
application. do we need to configure any specific intercepting rule in
general?

**Comment by mindfuckup** [comment]
No, SAML Raider should detect the supported SAML messages and display then the SAML Raider in the Proxy tab while intercepting and also in the proxy history. Either the SOAP message is a custom format or the detection in SAML Raider does something wrong.

**Comment by boreddom** [comment]
here is an screen shot of how it is being intercepted in burp

**Comment by mindfuckup** [comment]
Sorry, that mail attachment is not shown on GitHub.

**Comment by boreddom** [comment]
Does  it support  older version of SAML  like 1.0 as well?

**Comment by mindfuckup** [comment]
No, SAML 1.0 and 2.0 are not compatible and our extension was built and tested for SAML 2.0. Version 1.0 was not in scope and not tested. Would be more accidental if SAML 1.0 would also work.

**Comment by mindfuckup** [comment]
SAML 1.0 will not be supported. I have never seen SAML 1.0 in action. It's probbably not worth implementing it in SAML Raider.
