### ISSUE TITLE
SAML Comment attack

### ISSUE THREAD

**Issue by dobin** [SAMLRaider/SAMLRaider#25]
Maybe something useful to implement?
https://duo.com/blog/duo-finds-saml-vulnerabilities-affecting-multiple-implementations

**Comment by mindfuckup** [comment]
As far as I understand this vulnerability, this is nothing SAMLRaider could do automagically. This can be done by the pentester manually by inserting an HTML comment and an arbitrary suffix. Or did I miss something and this could be done in a more technical way?

**Comment by dobin** [comment]
Hmm, it may be not a generic enough attack to perform automagically.
