### ISSUE TITLE
[Java Updates] Make compatible for Java versions >=9/10/11

### ISSUE THREAD

**Issue by nks0ne** [SAMLRaider/SAMLRaider#29]
The main problem seems to be:

> java.lang.RuntimeException: java.lang.NoSuchMethodError: com.sun.org.apache.xml.internal.serialize.OutputFormat.<init>(Lorg/w3c/dom/Document;)V

Which renders SAMLRaider useless when using a newer JDK/JRE.

Some information:
http://openjdk.java.net/projects/jigsaw/talks/prepare-for-jdk9-j1-2016.pdf

**Comment by nks0ne** [comment]
Current workaround:
Use an older version of java. (1.8 is working as expected)

**Comment by mindfuckup** [comment]
Thx. I'll fix that in the next version.

**Comment by 0x4d4e** [comment]
I have the same issue with the bundled OpenJDK JRE in recent Burp 2.0 versions:

```
# ./java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by muse-enthusiast** [comment]
@mindfuckup When is your latest version coming out? Facing the same problem since the lastest Burp version (currently running v2.0.15 beta).

**Comment by mindfuckup** [comment]
Hi

I'm not sure yet. But my employer should give me some days this year which I can use to work on SAML Raider. This issue has high priority.

As a workaround: You could use the non-bundled version of Burp and use an older JRE.

**Comment by lxp** [comment]
It looks like the issue was fixed here: https://github.com/PortSwigger/saml-raider/commit/69844d1dc883de2ae8142d2282c5c0cc1e9a2edd

**Comment by mindfuckup** [comment]
This is now fixed. Thanks @lxp for the hint! New release: https://github.com/SAMLRaider/SAMLRaider/releases/tag/v1.2.2
