### ISSUE TITLE
Collecting example SAML Assertions

### ISSUE THREAD

**Issue by mindfuckup** [SAMLRaider/SAMLRaider#3]
I think it would be a good idea to collect various SAML assertions in a central directory. These can be useful for testing our Burp Extension.

I propose a new folder `examples` on the top level. The files are named after the IdP.

For example the one from the Issue #1 could be stored as `examples/salesforce`.

What do you @RouLee think?

:)

Grz

**Comment by RouLee** [comment]
Yeah I think this would be helpful.
At the moment, the assertions are in the test classes as a Java String.

@mindfuckup  In which format should the assertions be stored? ;)
Cheers

**Comment by mindfuckup** [comment]
May be like this one: https://github.com/SAMLRaider/SAMLRaider/blob/master/scripts/samltest/saml_response ?

**Comment by mindfuckup** [comment]
We should save them as a human-readable XML and like the encoded POST parameter. See some examples here: https://github.com/SAMLRaider/SAMLRaider/tree/master/scripts/samltest.
