### ISSUE TITLE
Can you please explain how i can edit a SAML assertion?

### ISSUE THREAD

**Issue by dimpol** [SAMLRaider/SAMLRaider#9]
Since i am new on web app pentesting. Can you please explain in detail how i can edit an original SAML assertion captured by SAMLRaider on burp?
For example to check if I can login as another user with the edited assertion

On a presentation of yours I saw the example to manipulate the certificates etc but on the assertion editing part the details were missing.

Can you please explain, step by step, how can i edit the original assertion and then send it via burp?

**Comment by mindfuckup** [comment]
Hi

The following steps will do it:

- Configure Burp as the Proxy in your browser
- Visit the site you like to test
- Enable the intercepting proxy in Burp
- Do a normal login
- If the login procedure is done using SAML, then the SAMLRaider tab will appear next to the "Hex" view.
- So you can modify the SAML Assertion
- Press "forward" to send the modified SAML Assertion.

You can see it here:

![](https://raw.githubusercontent.com/SAMLRaider/SAMLRaider/master/doc/message_editor.png)

If the SAMLRaider Tab does not appear, the login is not done using SAML or our extension has a bug.
Then we would be happy to get your assertion to fix it.

Thanks

**Comment by dimpol** [comment]
You are very helpful. The problem was i was using Oracle java and when i clicked on the assertion i could not modify it. When i returned to open jdk everything was perfect.

**Comment by mindfuckup** [comment]
OK, thanks for your confirmation. We will keep in mind that there may be issues in the Oracle JVM. So I will close the issue. Thanks!
